### PR TITLE
Add Hamburger Menu with Toggle Functionality

### LINKED ISSUE #13: Work on a responsive design for the WDX180 and the Table of Contents
There's an issue with the responsive version of the side Table of Contents menu on some screen sizes (see attached screenshot):

Screenshot 2023-10-03 at 12 41 07

To see the issue, visit the following link: [https://in-tech-gration.github.io/WDX-180/curriculum/week01/](https://in-tech-gration.github.io/WDX-180/curriculum/week01/)

**Requirements:**

- Work on a responsive side menu
- Create a branch named `feature/responsive-toc` before starting to work on the task
- Contact the project manager (@kostasx) for more information

**UPDATE 06/10/2023**: 

"The problem regarding responsiveness persists on smaller screens because of this back button doesn't work properly."

### PR DESCRIPTION
**Pull request by MaryRichelle**
This pull request introduces a responsive hamburger menu that toggles the side navigation menu on click.
Please review and let me know if there are any updates or improvements needed.
closes #13

### CODE REVIEW

**Comment by patric94** [comment]
@MaryRichelle   Two things that need to be done:
- the hamburger icon should change to the close icon after the button is clicked more than twice
- on mobile view the button should NOT be displayed
Additionally, I think it would be nice if you could try solving the issue on screen sizes with width less than 1200px (approximately) where the ToC overlaps with the main content of the page.

**Comment by MaryRichelle** [comment]
@patric94 
 I’ve fixed the issues across all screen sizes. Could you please check and let me know if it looks better now? Also, let me know if there are any additional changes needed for the mobile view whether the button should be displayed or not.

**Comment by patric94** [comment]
@MaryRichelle 
Good job Mary!
The mobile versions looks good! I think the hamburger menu should stay on top along with the theme toggler and not be displayed if you scroll down the content of the page. Also the ToC should be closed when you click on an item inside it.
As for the desktop mode, you've removed the repsosiveness of the ToC from a previous commit of yours and in some specific widths (>1200px and < 1700px) the ToC gets on top of the main content. I think the following code should be added after line `//>> SIDE NAVIGATION (ToC) RESPONSIVENESS`: 
```
nav#side-toc{
  @media (width >= 1200px) {
    width: 20vw;
    padding-left: 0.75rem
  }
}
```
We can schedule a call on Slack during this week. if you are available, to discuss it.

**Comment by kostasx** [comment]
Thank you for your contribution @MaryRichelle! 💯

**Pull request merged**
